create index firstQueryIndex1 on payment(payment_date);
create index firstQueryIndex2 on payment using hash(payment_date);
create index firstQueryIndex3 on payment(payment_id);
create index firstQueryIndex4 on payment using hash(payment_id);
create index firstQueryIndex5 on payment(rental_id);
create index firstQueryIndex6 on payment using hash(rental_id);
create index firstQueryIndex7 on payment(payment_date,payment_id);
create index firstQueryIndex8 on payment(payment_id,payment_date);
create index firstQueryIndex9 on payment(payment_date,rental_id);
create index firstQueryIndex10 on payment(rental_id,payment_date);
create index firstQueryIndex11 on payment(payment_id,rental_id);
create index firstQueryIndex12 on payment(rental_id,payment_id);
create index firstQueryIndex13 on payment(payment_date,payment_id,rental_id);
create index firstQueryIndex14 on payment(payment_date,rental_id,payment_id);
create index firstQueryIndex15 on payment(payment_id,payment_date,rental_id);
create index firstQueryIndex16 on payment(payment_id,rental_id,payment_date);
create index firstQueryIndex17 on payment(rental_id,payment_date,payment_id);
create index firstQueryIndex18 on payment(rental_id,payment_id,payment_date);
create index firstQueryIndex19 on rental(staff_id);
create index firstQueryIndex20 on rental using hash(staff_id);
create index firstQueryIndex21 on rental(customer_id);
create index firstQueryIndex22 on rental using hash(customer_id);
create index firstQueryIndex23 on rental(last_update);
create index firstQueryIndex24 on rental using hash(last_update);
create index firstQueryIndex25 on rental(rental_id);
create index firstQueryIndex26 on rental using hash(rental_id);
create index firstQueryIndex27 on rental(customer_id,staff_id);
create index firstQueryIndex28 on rental(staff_id,customer_id);
create index firstQueryIndex29 on rental(last_update,staff_id);
create index firstQueryIndex30 on rental(staff_id,last_update);
create index firstQueryIndex31 on rental(rental_id,staff_id);
create index firstQueryIndex32 on rental(staff_id,rental_id);
create index firstQueryIndex33 on rental(customer_id,last_update);
create index firstQueryIndex34 on rental(last_update,customer_id);
create index firstQueryIndex35 on rental(customer_id,rental_id);
create index firstQueryIndex36 on rental(rental_id,customer_id);
create index firstQueryIndex37 on rental(last_update,rental_id);
create index firstQueryIndex38 on rental(rental_id,last_update);
create index firstQueryIndex39 on rental(customer_id,last_update,staff_id);
create index firstQueryIndex40 on rental(customer_id,staff_id,last_update);
create index firstQueryIndex41 on rental(last_update,customer_id,staff_id);
create index firstQueryIndex42 on rental(last_update,staff_id,customer_id);
create index firstQueryIndex43 on rental(staff_id,customer_id,last_update);
create index firstQueryIndex44 on rental(staff_id,last_update,customer_id);
create index firstQueryIndex45 on rental(customer_id,rental_id,staff_id);
create index firstQueryIndex46 on rental(customer_id,staff_id,rental_id);
create index firstQueryIndex47 on rental(rental_id,customer_id,staff_id);
create index firstQueryIndex48 on rental(rental_id,staff_id,customer_id);
create index firstQueryIndex49 on rental(staff_id,customer_id,rental_id);
create index firstQueryIndex50 on rental(staff_id,rental_id,customer_id);
create index firstQueryIndex51 on rental(last_update,rental_id,staff_id);
create index firstQueryIndex52 on rental(last_update,staff_id,rental_id);
create index firstQueryIndex53 on rental(rental_id,last_update,staff_id);
create index firstQueryIndex54 on rental(rental_id,staff_id,last_update);
create index firstQueryIndex55 on rental(staff_id,last_update,rental_id);
create index firstQueryIndex56 on rental(staff_id,rental_id,last_update);
create index firstQueryIndex57 on rental(customer_id,last_update,rental_id);
create index firstQueryIndex58 on rental(customer_id,rental_id,last_update);
create index firstQueryIndex59 on rental(last_update,customer_id,rental_id);
create index firstQueryIndex60 on rental(last_update,rental_id,customer_id);
create index firstQueryIndex61 on rental(rental_id,customer_id,last_update);
create index firstQueryIndex62 on rental(rental_id,last_update,customer_id);
create index firstQueryIndex63 on rental(customer_id,last_update,rental_id,staff_id);
create index firstQueryIndex64 on rental(customer_id,last_update,staff_id,rental_id);
create index firstQueryIndex65 on rental(customer_id,rental_id,last_update,staff_id);
create index firstQueryIndex66 on rental(customer_id,rental_id,staff_id,last_update);
create index firstQueryIndex67 on rental(customer_id,staff_id,last_update,rental_id);
create index firstQueryIndex68 on rental(customer_id,staff_id,rental_id,last_update);
create index firstQueryIndex69 on rental(last_update,customer_id,rental_id,staff_id);
create index firstQueryIndex70 on rental(last_update,customer_id,staff_id,rental_id);
create index firstQueryIndex71 on rental(last_update,rental_id,customer_id,staff_id);
create index firstQueryIndex72 on rental(last_update,rental_id,staff_id,customer_id);
create index firstQueryIndex73 on rental(last_update,staff_id,customer_id,rental_id);
create index firstQueryIndex74 on rental(last_update,staff_id,rental_id,customer_id);
create index firstQueryIndex75 on rental(rental_id,customer_id,last_update,staff_id);
create index firstQueryIndex76 on rental(rental_id,customer_id,staff_id,last_update);
create index firstQueryIndex77 on rental(rental_id,last_update,customer_id,staff_id);
create index firstQueryIndex78 on rental(rental_id,last_update,staff_id,customer_id);
create index firstQueryIndex79 on rental(rental_id,staff_id,customer_id,last_update);
create index firstQueryIndex80 on rental(rental_id,staff_id,last_update,customer_id);
create index firstQueryIndex81 on rental(staff_id,customer_id,last_update,rental_id);
create index firstQueryIndex82 on rental(staff_id,customer_id,rental_id,last_update);
create index firstQueryIndex83 on rental(staff_id,last_update,customer_id,rental_id);
create index firstQueryIndex84 on rental(staff_id,last_update,rental_id,customer_id);
create index firstQueryIndex85 on rental(staff_id,rental_id,customer_id,last_update);
create index firstQueryIndex86 on rental(staff_id,rental_id,last_update,customer_id);
create index firstQueryIndex87 on customer(customer_id);
create index firstQueryIndex88 on customer using hash(customer_id);
create index firstQueryIndex89 on customer(active);
create index firstQueryIndex90 on customer using hash(active);
create index firstQueryIndex91 on customer(active,customer_id);
create index firstQueryIndex92 on customer(customer_id,active);
create index secondQueryIndex1 on film(rental_rate);
create index secondQueryIndex2 on film using hash(rental_rate);
create index secondQueryIndex3 on film(release_year);
create index secondQueryIndex4 on film using hash(release_year);
create index secondQueryIndex5 on film(title);
create index secondQueryIndex6 on film using hash(title);
create index secondQueryIndex7 on film(film_id);
create index secondQueryIndex8 on film using hash(film_id);
create index secondQueryIndex9 on film(release_year,rental_rate);
create index secondQueryIndex10 on film(rental_rate,release_year);
create index secondQueryIndex11 on film(rental_rate,title);
create index secondQueryIndex12 on film(title,rental_rate);
create index secondQueryIndex13 on film(film_id,rental_rate);
create index secondQueryIndex14 on film(rental_rate,film_id);
create index secondQueryIndex15 on film(release_year,title);
create index secondQueryIndex16 on film(title,release_year);
create index secondQueryIndex17 on film(film_id,release_year);
create index secondQueryIndex18 on film(release_year,film_id);
create index secondQueryIndex19 on film(film_id,title);
create index secondQueryIndex20 on film(title,film_id);
create index secondQueryIndex21 on film(release_year,rental_rate,title);
create index secondQueryIndex22 on film(release_year,title,rental_rate);
create index secondQueryIndex23 on film(rental_rate,release_year,title);
create index secondQueryIndex24 on film(rental_rate,title,release_year);
create index secondQueryIndex25 on film(title,release_year,rental_rate);
create index secondQueryIndex26 on film(title,rental_rate,release_year);
create index secondQueryIndex27 on film(film_id,release_year,rental_rate);
create index secondQueryIndex28 on film(film_id,rental_rate,release_year);
create index secondQueryIndex29 on film(release_year,film_id,rental_rate);
create index secondQueryIndex30 on film(release_year,rental_rate,film_id);
create index secondQueryIndex31 on film(rental_rate,film_id,release_year);
create index secondQueryIndex32 on film(rental_rate,release_year,film_id);
create index secondQueryIndex33 on film(film_id,rental_rate,title);
create index secondQueryIndex34 on film(film_id,title,rental_rate);
create index secondQueryIndex35 on film(rental_rate,film_id,title);
create index secondQueryIndex36 on film(rental_rate,title,film_id);
create index secondQueryIndex37 on film(title,film_id,rental_rate);
create index secondQueryIndex38 on film(title,rental_rate,film_id);
create index secondQueryIndex39 on film(film_id,release_year,title);
create index secondQueryIndex40 on film(film_id,title,release_year);
create index secondQueryIndex41 on film(release_year,film_id,title);
create index secondQueryIndex42 on film(release_year,title,film_id);
create index secondQueryIndex43 on film(title,film_id,release_year);
create index secondQueryIndex44 on film(title,release_year,film_id);
create index secondQueryIndex45 on film(film_id,release_year,rental_rate,title);
create index secondQueryIndex46 on film(film_id,release_year,title,rental_rate);
create index secondQueryIndex47 on film(film_id,rental_rate,release_year,title);
create index secondQueryIndex48 on film(film_id,rental_rate,title,release_year);
create index secondQueryIndex49 on film(film_id,title,release_year,rental_rate);
create index secondQueryIndex50 on film(film_id,title,rental_rate,release_year);
create index secondQueryIndex51 on film(release_year,film_id,rental_rate,title);
create index secondQueryIndex52 on film(release_year,film_id,title,rental_rate);
create index secondQueryIndex53 on film(release_year,rental_rate,film_id,title);
create index secondQueryIndex54 on film(release_year,rental_rate,title,film_id);
create index secondQueryIndex55 on film(release_year,title,film_id,rental_rate);
create index secondQueryIndex56 on film(release_year,title,rental_rate,film_id);
create index secondQueryIndex57 on film(rental_rate,film_id,release_year,title);
create index secondQueryIndex58 on film(rental_rate,film_id,title,release_year);
create index secondQueryIndex59 on film(rental_rate,release_year,film_id,title);
create index secondQueryIndex60 on film(rental_rate,release_year,title,film_id);
create index secondQueryIndex61 on film(rental_rate,title,film_id,release_year);
create index secondQueryIndex62 on film(rental_rate,title,release_year,film_id);
create index secondQueryIndex63 on film(title,film_id,release_year,rental_rate);
create index secondQueryIndex64 on film(title,film_id,rental_rate,release_year);
create index secondQueryIndex65 on film(title,release_year,film_id,rental_rate);
create index secondQueryIndex66 on film(title,release_year,rental_rate,film_id);
create index secondQueryIndex67 on film(title,rental_rate,film_id,release_year);
create index secondQueryIndex68 on film(title,rental_rate,release_year,film_id);
create index thirdQueryIndex1 on payment(payment_id);
create index thirdQueryIndex2 on payment using hash(payment_id);
create index thirdQueryIndex3 on payment(amount);
create index thirdQueryIndex4 on payment using hash(amount);
create index thirdQueryIndex5 on payment(rental_id);
create index thirdQueryIndex6 on payment using hash(rental_id);
create index thirdQueryIndex7 on payment(amount,payment_id);
create index thirdQueryIndex8 on payment(payment_id,amount);
create index thirdQueryIndex9 on payment(payment_id,rental_id);
create index thirdQueryIndex10 on payment(rental_id,payment_id);
create index thirdQueryIndex11 on payment(amount,rental_id);
create index thirdQueryIndex12 on payment(rental_id,amount);
create index thirdQueryIndex13 on payment(amount,payment_id,rental_id);
create index thirdQueryIndex14 on payment(amount,rental_id,payment_id);
create index thirdQueryIndex15 on payment(payment_id,amount,rental_id);
create index thirdQueryIndex16 on payment(payment_id,rental_id,amount);
create index thirdQueryIndex17 on payment(rental_id,amount,payment_id);
create index thirdQueryIndex18 on payment(rental_id,payment_id,amount);
create index thirdQueryIndex19 on rental(rental_id);
create index thirdQueryIndex20 on rental using hash(rental_id);
create index thirdQueryIndex21 on rental(inventory_id);
create index thirdQueryIndex22 on rental using hash(inventory_id);
create index thirdQueryIndex23 on rental(customer_id);
create index thirdQueryIndex24 on rental using hash(customer_id);
create index thirdQueryIndex25 on rental(inventory_id,rental_id);
create index thirdQueryIndex26 on rental(rental_id,inventory_id);
create index thirdQueryIndex27 on rental(customer_id,rental_id);
create index thirdQueryIndex28 on rental(rental_id,customer_id);
create index thirdQueryIndex29 on rental(customer_id,inventory_id);
create index thirdQueryIndex30 on rental(inventory_id,customer_id);
create index thirdQueryIndex31 on rental(customer_id,inventory_id,rental_id);
create index thirdQueryIndex32 on rental(customer_id,rental_id,inventory_id);
create index thirdQueryIndex33 on rental(inventory_id,customer_id,rental_id);
create index thirdQueryIndex34 on rental(inventory_id,rental_id,customer_id);
create index thirdQueryIndex35 on rental(rental_id,customer_id,inventory_id);
create index thirdQueryIndex36 on rental(rental_id,inventory_id,customer_id);
create index thirdQueryIndex37 on inventory(inventory_id);
create index thirdQueryIndex38 on inventory using hash(inventory_id);
create index thirdQueryIndex39 on inventory(film_id);
create index thirdQueryIndex40 on inventory using hash(film_id);
create index thirdQueryIndex41 on inventory(film_id,inventory_id);
create index thirdQueryIndex42 on inventory(inventory_id,film_id);
create index thirdQueryIndex43 on film(film_id);
create index thirdQueryIndex44 on film using hash(film_id);
create index thirdQueryIndex45 on film(title);
create index thirdQueryIndex46 on film using hash(title);
create index thirdQueryIndex47 on film(release_year);
create index thirdQueryIndex48 on film using hash(release_year);
create index thirdQueryIndex49 on film(rating);
create index thirdQueryIndex50 on film using hash(rating);
create index thirdQueryIndex51 on film(film_id,title);
create index thirdQueryIndex52 on film(title,film_id);
create index thirdQueryIndex53 on film(film_id,release_year);
create index thirdQueryIndex54 on film(release_year,film_id);
create index thirdQueryIndex55 on film(film_id,rating);
create index thirdQueryIndex56 on film(rating,film_id);
create index thirdQueryIndex57 on film(release_year,title);
create index thirdQueryIndex58 on film(title,release_year);
create index thirdQueryIndex59 on film(rating,title);
create index thirdQueryIndex60 on film(title,rating);
create index thirdQueryIndex61 on film(rating,release_year);
create index thirdQueryIndex62 on film(release_year,rating);
create index thirdQueryIndex63 on film(film_id,release_year,title);
create index thirdQueryIndex64 on film(film_id,title,release_year);
create index thirdQueryIndex65 on film(release_year,film_id,title);
create index thirdQueryIndex66 on film(release_year,title,film_id);
create index thirdQueryIndex67 on film(title,film_id,release_year);
create index thirdQueryIndex68 on film(title,release_year,film_id);
create index thirdQueryIndex69 on film(film_id,rating,title);
create index thirdQueryIndex70 on film(film_id,title,rating);
create index thirdQueryIndex71 on film(rating,film_id,title);
create index thirdQueryIndex72 on film(rating,title,film_id);
create index thirdQueryIndex73 on film(title,film_id,rating);
create index thirdQueryIndex74 on film(title,rating,film_id);
create index thirdQueryIndex75 on film(film_id,rating,release_year);
create index thirdQueryIndex76 on film(film_id,release_year,rating);
create index thirdQueryIndex77 on film(rating,film_id,release_year);
create index thirdQueryIndex78 on film(rating,release_year,film_id);
create index thirdQueryIndex79 on film(release_year,film_id,rating);
create index thirdQueryIndex80 on film(release_year,rating,film_id);
create index thirdQueryIndex81 on film(rating,release_year,title);
create index thirdQueryIndex82 on film(rating,title,release_year);
create index thirdQueryIndex83 on film(release_year,rating,title);
create index thirdQueryIndex84 on film(release_year,title,rating);
create index thirdQueryIndex85 on film(title,rating,release_year);
create index thirdQueryIndex86 on film(title,release_year,rating);
create index thirdQueryIndex87 on film(film_id,rating,release_year,title);
create index thirdQueryIndex88 on film(film_id,rating,title,release_year);
create index thirdQueryIndex89 on film(film_id,release_year,rating,title);
create index thirdQueryIndex90 on film(film_id,release_year,title,rating);
create index thirdQueryIndex91 on film(film_id,title,rating,release_year);
create index thirdQueryIndex92 on film(film_id,title,release_year,rating);
create index thirdQueryIndex93 on film(rating,film_id,release_year,title);
create index thirdQueryIndex94 on film(rating,film_id,title,release_year);
create index thirdQueryIndex95 on film(rating,release_year,film_id,title);
create index thirdQueryIndex96 on film(rating,release_year,title,film_id);
create index thirdQueryIndex97 on film(rating,title,film_id,release_year);
create index thirdQueryIndex98 on film(rating,title,release_year,film_id);
create index thirdQueryIndex99 on film(release_year,film_id,rating,title);
create index thirdQueryIndex100 on film(release_year,film_id,title,rating);
create index thirdQueryIndex101 on film(release_year,rating,film_id,title);
create index thirdQueryIndex102 on film(release_year,rating,title,film_id);
create index thirdQueryIndex103 on film(release_year,title,film_id,rating);
create index thirdQueryIndex104 on film(release_year,title,rating,film_id);
create index thirdQueryIndex105 on film(title,film_id,rating,release_year);
create index thirdQueryIndex106 on film(title,film_id,release_year,rating);
create index thirdQueryIndex107 on film(title,rating,film_id,release_year);
create index thirdQueryIndex108 on film(title,rating,release_year,film_id);
create index thirdQueryIndex109 on film(title,release_year,film_id,rating);
create index thirdQueryIndex110 on film(title,release_year,rating,film_id);
create index thirdQueryIndex111 on customer(customer_id);
create index thirdQueryIndex112 on customer using hash(customer_id);
create index thirdQueryIndex113 on customer(first_name);
create index thirdQueryIndex114 on customer using hash(first_name);
create index thirdQueryIndex115 on customer(customer_id,first_name);
create index thirdQueryIndex116 on customer(first_name,customer_id);
create index thirdQueryIndex117 on film_actor(actor_id);
create index thirdQueryIndex118 on film_actor using hash(actor_id);
create index thirdQueryIndex119 on film_actor(film_id);
create index thirdQueryIndex120 on film_actor using hash(film_id);
create index thirdQueryIndex121 on film_actor(actor_id,film_id);
create index thirdQueryIndex122 on film_actor(film_id,actor_id);
create index thirdQueryIndex123 on actor(actor_id);
create index thirdQueryIndex124 on actor using hash(actor_id);
create index thirdQueryIndex125 on actor(first_name);
create index thirdQueryIndex126 on actor using hash(first_name);
create index thirdQueryIndex127 on actor(actor_id,first_name);
create index thirdQueryIndex128 on actor(first_name,actor_id);