# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\x1e\n\x0eReverseMessage\x12\x0c\n\x04text\x18\x01 \x01(\t\"*\n\x16ReverseMessageResponse\x12\x10\n\x08reversed\x18\x01 \x01(\t\"+\n\x0cSplitMessage\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05\x64\x65lim\x18\x02 \x01(\t\"3\n\x14SplitMessageResponse\x12\x0c\n\x04size\x18\x01 \x01(\x05\x12\r\n\x05parts\x18\x02 \x03(\t\"\x1d\n\x0eIsprimeMessage\x12\x0b\n\x03num\x18\x01 \x01(\x05\")\n\x16IsprimeMessageResponse\x12\x0f\n\x07verdict\x18\x01 \x01(\t2\xb8\x01\n\x07Service\x12\x39\n\rServerReverse\x12\x0f.ReverseMessage\x1a\x17.ReverseMessageResponse\x12\x33\n\x0bServerSplit\x12\r.SplitMessage\x1a\x15.SplitMessageResponse\x12=\n\rServerIsprime\x12\x0f.IsprimeMessage\x1a\x17.IsprimeMessageResponse(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REVERSEMESSAGE._serialized_start=17
  _REVERSEMESSAGE._serialized_end=47
  _REVERSEMESSAGERESPONSE._serialized_start=49
  _REVERSEMESSAGERESPONSE._serialized_end=91
  _SPLITMESSAGE._serialized_start=93
  _SPLITMESSAGE._serialized_end=136
  _SPLITMESSAGERESPONSE._serialized_start=138
  _SPLITMESSAGERESPONSE._serialized_end=189
  _ISPRIMEMESSAGE._serialized_start=191
  _ISPRIMEMESSAGE._serialized_end=220
  _ISPRIMEMESSAGERESPONSE._serialized_start=222
  _ISPRIMEMESSAGERESPONSE._serialized_end=263
  _SERVICE._serialized_start=266
  _SERVICE._serialized_end=450
# @@protoc_insertion_point(module_scope)
