# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class ServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ServerReverse = channel.unary_unary(
                '/Service/ServerReverse',
                request_serializer=service__pb2.ReverseMessage.SerializeToString,
                response_deserializer=service__pb2.ReverseMessageResponse.FromString,
                )
        self.ServerSplit = channel.unary_unary(
                '/Service/ServerSplit',
                request_serializer=service__pb2.SplitMessage.SerializeToString,
                response_deserializer=service__pb2.SplitMessageResponse.FromString,
                )
        self.ServerIsprime = channel.stream_stream(
                '/Service/ServerIsprime',
                request_serializer=service__pb2.IsprimeMessage.SerializeToString,
                response_deserializer=service__pb2.IsprimeMessageResponse.FromString,
                )


class ServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ServerReverse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerSplit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerIsprime(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ServerReverse': grpc.unary_unary_rpc_method_handler(
                    servicer.ServerReverse,
                    request_deserializer=service__pb2.ReverseMessage.FromString,
                    response_serializer=service__pb2.ReverseMessageResponse.SerializeToString,
            ),
            'ServerSplit': grpc.unary_unary_rpc_method_handler(
                    servicer.ServerSplit,
                    request_deserializer=service__pb2.SplitMessage.FromString,
                    response_serializer=service__pb2.SplitMessageResponse.SerializeToString,
            ),
            'ServerIsprime': grpc.stream_stream_rpc_method_handler(
                    servicer.ServerIsprime,
                    request_deserializer=service__pb2.IsprimeMessage.FromString,
                    response_serializer=service__pb2.IsprimeMessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ServerReverse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service/ServerReverse',
            service__pb2.ReverseMessage.SerializeToString,
            service__pb2.ReverseMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ServerSplit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service/ServerSplit',
            service__pb2.SplitMessage.SerializeToString,
            service__pb2.SplitMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ServerIsprime(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/Service/ServerIsprime',
            service__pb2.IsprimeMessage.SerializeToString,
            service__pb2.IsprimeMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
